setup_ansible_pull: true
dotfiles: true
oh_my_zsh: true
vscode: false

install_apple_office: false
install_garageband: false
install_imovie: false
mac_app_store: false

install_mas_apps:
  - 1352778147 # Bitwarden
remove_mas_apps: []

install_sync_tools: false
sync_formulae: []
sync_casks:
  - nextcloud
  - syncthing

install_misc_apps: false
misc_formulae: []
misc_casks:
  - iterm2
  - the-unarchiver

install_entertainment_apps: false
entertainment_formulae: []
entertainment_casks:
  - spotify
  - vlc

install_media_tools: false
media_formulae: []
media_casks:
  - handbrake
  - makemkv

install_kube_apps: false
kube_formulae:
  - argocd
  - kubernetes-cli
  - derailed/k9s/k9s
  - kubectx
  - podman-compose
kube_casks:
  - openlens
  - podman-desktop

install_dev_tools: false
devtools_formulae:
  - ansible-lint
  - gh
  - git
devtools_casks: []

install_common_cli_tools: false
common_cli_formulae:
  - bitwarden-cli
  - zstd
common_cli_casks: []

install_aws_tools: false
aws_formulae:
  - awscli
  - s3cmd
aws_casks: []

install_other_formulae: []
install_other_casks: []
remove_other_formulae: []
remove_other_casks: []
