- hosts: all
  gather_facts: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Check for local options file
      ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.setup-options"
      register: local_options_file

    - name: Include local configuration
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'HOME') }}/.setup-options"
      when: local_options_file.stat.exists

    - name: Update package managers
      block:
        - name: Update homewbrew packages
          community.general.homebrew:
            update_homebrew: true
          when: ansible_pkg_mgr == "homebrew"

    - name: Get list of installed packages
      block:
        - name: Get installed homebew packages
          ansible.builtin.import_tasks: tasks/homebrew_list.yml
          when: ansible_pkg_mgr == "homebrew"

  tasks:
    - ansible.builtin.import_tasks: tasks/ansible-pull-cron.yml
      when: setup_ansible_pull
    - ansible.builtin.import_tasks: tasks/dotfiles.yml
      when: dotfiles
    - ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
      when: oh_my_zsh
    - ansible.builtin.import_tasks: tasks/vscode.yml
      when: vscode
    - ansible.builtin.import_tasks: tasks/mac-app-store.yml
      when: mac_app_store
    - name: Manage sync tools
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_sync_tools | default(false) }}"
        groupname: sync
        formulae: "{{ sync_formulae }}"
        casks: "{{ sync_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage misc apps
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_misc_apps | default(false) }}"
        groupname: misc
        formulae: "{{ misc_formulae }}"
        casks: "{{ misc_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage entertainment apps
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_entertainment_apps | default(false) }}"
        groupname: entertainment
        formuale: "{{ entertainment_formulae }}"
        casks: "{{ entertainment_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage media tools
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_media_tools | default(false) }}"
        groupname: media
        formulae: "{{ media_formulae }}"
        casks: "{{ media_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage kube tools
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_kube_apps | default(false) }}"
        groupname: kube
        formulae: "{{ kube_formulae }}"
        casks: "{{ kube_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage dev tools
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_dev_tools | default(false) }}"
        groupname: dev
        formulae: "{{ devtools_formulae }}"
        casks: "{{ devtools_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage common cli tools
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_common_cli_tools | default(false) }}"
        groupname: common cli
        formulae: "{{ common_cli_formulae }}"
        casks: "{{ common_cli_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage aws tools
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: "{{ install_aws_tools | default(false) }}"
        groupname: aws
        formulae: "{{ aws_formulae }}"
        casks: "{{ aws_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true

    - name: Manage other packages
      ansible.builtin.import_tasks: tasks/homebrew_packages.yml
      vars:
        enabled: true
        groupname: other
        formulae: "{{ install_other_formulae }}"
        casks: "{{ install_other_casks }}"
      when:
        - ansible_pkg_mgr == "homebrew"
      ignore_errors: true
