- hosts: all
  gather_facts: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Create local config
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.setup/default.config.yml"
        dest: "{{ lookup('env', 'HOME') }}/.setup-options"
        force: false

    - name: Include local configuration
      include_vars: "{{ item }}"
      loop:
        - "{{ lookup('env', 'HOME') }}/.setup-options"

    - name: Update package managers
      block:
        - name: Update homewbrew packages
          community.general.homebrew:
            update_homebrew: true
          when: ansible_pkg_mgr == "homebrew"
    - name: Get list of installed packages
      block:
        - name: Get installed homebew packages
          import_tasks: tasks/homebrew_list.yml
          when: ansible_pkg_mgr == "homebrew"

  tasks:
    - import_tasks: tasks/ansible-pull-cron.yml
      when: setup_ansible_pull
    - import_tasks: tasks/dotfiles.yml
      when: dotfiles
    - import_tasks: tasks/oh-my-zsh.yml
      when: oh_my_zsh
    - import_tasks: tasks/vscode.yml
      when: vscode
    - import_tasks: tasks/mac-app-store.yml
      when: mac_app_store
    - name: Manage sync tools
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: sync
        install_formulae: "{{ sync_formulae }}"
        install_casks: "{{ sync_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_sync_tools and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage misc apps
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: misc
        install_formulae: "{{ misc_formulae }}"
        install_casks: "{{ misc_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_misc_apps and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage entertainment apps
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: entertainment
        install_formulae: "{{ entertainment_formulae }}"
        install_casks: "{{ entertainment_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_entertainment_apps and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage media tools
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: media
        install_formulae: "{{ media_formulae }}"
        install_casks: "{{ media_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_media_tools and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage kube tools
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: kube
        install_formulae: "{{ kube_formulae }}"
        install_casks: "{{ kube_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_kube_apps and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage dev tools
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: dev
        install_formulae: "{{ devtools_formulae }}"
        install_casks: "{{ devtools_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_dev_tools and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage common cli tools
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: common cli
        install_formulae: "{{ common_cli_formulae }}"
        install_casks: "{{ common_cli_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_common_cli_tools and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage aws tools
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: aws
        install_formulae: "{{ aws_formulae }}"
        install_casks: "{{ aws_casks }}"
        remove_formulae: []
        remove_casks: []
      when: install_aws_tools and ansible_pkg_mgr == "homebrew"
      ignore_errors: true
    - name: Manage other packages
      import_tasks: tasks/homebrew_packages.yml
      vars:
        groupname: other
        install_formulae: "{{ install_other_formulae }}"
        install_casks: "{{ install_other_casks }}"
        remove_formulae: "{{ remove_other_formulae }}"
        remove_casks: "{{ remove_other_casks }}"
      when: ansible_pkg_mgr == "homebrew"
      ignore_errors: true
