- name: Disable cron email
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: ""

- name: Setup cron PATH
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

- name: Ansible-pull cron job
  ansible.builtin.cron:
    name: ansible-pull quarter-hourly
    minute: "*/15"
    job: "{{ lookup('env', 'HOME') }}/.setup/run-ansible-pull.sh -o >{{ lookup('env', 'HOME') }}/.ansible.log 2>&1"

- name: Ansible-pull reboot cron
  ansible.builtin.cron:
    name: ansible-pull reboot
    special_time: reboot
    job: "{{ lookup('env', 'HOME') }}/.setup/run-ansible-pull.sh -e ON_REBOOT=true >{{ lookup('env', 'HOME') }}/.ansible.log 2>&1"
