- name: Disable cron email
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: ""

- name: Setup cron PATH
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: "/opt/homebrew/bin:/usr/local/bin:$PATH"

- name: Ansible-pull cron job
  ansible.builtin.cron:
    name: ansible-pull quarter-hourly
    minute: "*/15"
    job: "{{ lookup('env', 'HOME') }}/.setup/run-ansible-pull.sh -o >/dev/null 2>&1"

- name: Ansible-pull reboot cron
  ansible.builtin.cron:
    name: ansible-pull reboot
    special_time: reboot
    job: "{{ lookup('env', 'HOME') }}/.setup/run-ansible-pull.sh -e ON_REBOOT=true >/dev/null 2>&1"
