- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/"
  loop:
    - files/.vimrc
    - files/.gitignore

- name: .zshrc
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Find full path to git-credential-manager
  ansible.builtin.command:
    cmd: which git-credential-manager
  register: gcm_path
  changed_when: false
  failed_when: gcm_path.rc != 0
  when: ansible_os_family != 'Windows'

- name: .gitconfig
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.template', 'templates/.gitconfig.j2') }}"
    create: true

- name: .ssh/config
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    block: "{{ lookup('ansible.builtin.file', 'files/ssh_config') }}"
    create: true
