- name: .vimrc
  ansible.builtin.copy:
    src: files/vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: .zprofile
  ansible.builtin.copy:
    src: files/zprofile
    dest: "{{ lookup('env', 'HOME') }}/.zprofile"

- name: .gitconfig
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.file', 'files/gitconfig') }}"