- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/"
  loop:
    - files/.vimrc
    - files/.zprofile
    - files/.gitignore

- name: Copy homebrew zprofile
  ansible.builtin.copy:
    src: files/.zprofile.homebrew
    dest: "{{ lookup('env', 'HOME') }}/.zprofile"
  when: ansible_pkg_mgr == "homebrew"

- name: Copy non-homebrew zprofile
  ansible.builtin.copy:
    src: files/.zprofile
    dest: "{{ lookup('env', 'HOME') }}/.zprofile"
  when: ansible_pkg_mgr != "homebrew"

- name: Make .gitconfig
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    state: touch

- name: .gitconfig
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.file', 'files/.gitconfig') }}"
