- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/"
  loop:
    - files/.vimrc
    - files/.gitignore

- name: .zshrc
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"

- name: .gitconfig
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.file', 'files/.gitconfig') }}"
    create: true

- name: .ssh/config
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    block: "{{ lookup('ansible.builtin.file', 'files/ssh_config') }}"
    create: true
