- name: '{{ enabled | ternary("Install", "Remove") }} homebrew formulae for {{ groupname }}'
  community.general.homebrew:
    name: "{{ formulae }}"
    state: '{{ enabled | ternary("latest", "absent") }}'
  when:
    - formulae | length > 0
    - formulae | difference(installed_brew_formulae.stdout_lines) | length > 0 or
      formulae | intersect(installed_brew_formulae.stdout_lines) | length > 0
    - enabled != "ignore"

- name: '{{ enabled | ternary("Install", "Remove") }} homebrew casks for {{ groupname }}'
  community.general.homebrew_cask:
    name: "{{ casks }}"
    state: '{{ enabled | ternary("present", "absent") }}'
    sudo_password: "{{ ansible_become_password | default() }}"
    install_options:
      - "force"
  when:
    - casks | length > 0
    - casks | difference(installed_brew_casks.stdout_lines) | length > 0 or
      casks | intersect(installed_brew_casks.stdout_lines) | length > 0
    - enabled != "ignore"