- name: Install OMZ
  ansible.builtin.shell:
    cmd: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

- name: Install OMZ auto-update plugin
  ansible.builtin.git:
    repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/autoupdate"

- name: Install powerlevel10k theme and font with homebrew
  block:
    - name: Tap repos for p10k
      community.general.homebrew_tap:
        name:
          - romkatv/powerlevel10k
          - homebrew/cask-fonts
        state: present
      when: "['romkatv/powerlevel10k', 'homebrew/cask-fonts'] | difference(brew_taps.stdout) | length > 0"
    - name: Install meslo fonts
      community.general.homebrew_cask:
        name:
          - font-meslo-for-powerline
      when: "['font-meslo-for-powerline'] | difference(installed_brew_casks.stdout) | length > 0"
      ignore_errors: true
    - name: Install powerlevel10k
      community.general.homebrew:
        name:
          - powerlevel10k
        state: present
      when: "['powerlevel10k'] | difference(installed_brew_formulae.stdout) | length > 0"
    - name: .zshrc
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'HOME') }}/"
        src: files/zshrc.homebrew
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
  when: ansible_pkg_mgr == "homebrew"

- name: Install powerlevel10k theme from git
  block:
    - name: Pull powerlevel10k theme
      ansible.builtin.shell:
        cmd: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
        creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    - name: .zshrc
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'HOME') }}/"
        src: files/zshrc
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
  when: ansible_pkg_mgr != "homebrew"

- name: .p10k.zsh
  ansible.builtin.copy:
    src: files/p10k.zsh
    dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
