- name: Install OMZ
  ansible.builtin.shell:
    cmd: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

- name: Install OMZ auto-update plugin
  ansible.builtin.git:
    repo: https://github.com/TamCore/autoupdate-oh-my-zsh-plugins.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/plugins/autoupdate"

- name: Install powerlevel10k theme and font with homebrew
  block:
    - name: Tap repos for fonts
      community.general.homebrew_tap:
        name: "{{ items }}"
        state: present
      vars:
        items:
          - 'homebrew/cask-fonts'
      when: "items | difference(brew_taps.stdout) | length > 0"
    - name: Install meslo fonts
      community.general.homebrew_cask:
        name: "{{ items }}"
      vars:
        items:
          - font-meslo-for-powerline
      when: "items | difference(installed_brew_casks.stdout) | length > 0"
      ignore_errors: true
    - name: Install powerlevel10k
      community.general.homebrew:
        name: "{{ items }}"
        state: present
      vars:
        items:
          - autoenv
          - powerlevel10k
      when: "items | difference(installed_brew_formulae.stdout) | length > 0"
  when: ansible_pkg_mgr == "homebrew"

- name: Install powerlevel10k theme from git
  block:
    - name: Pull powerlevel10k theme
      ansible.builtin.shell:
        cmd: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
        creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
  when: ansible_pkg_mgr != "homebrew"

- name: Install Meslo nerd fonts
  block:
    - name: Ensure local fonts dir exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        state: directory
    - ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Regular.ttf"
      register: regular
    - name: "Regular"
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Regular.ttf"
      when: not regular.stat.exists
    - ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Bold.ttf"
      register: bold
    - name: "Bold"
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Bold.ttf"
      when: not bold.stat.exists
    - ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Italic.ttf"
      register: italic
    - name: "Italic"
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Italic.ttf"
      when: not italic.stat.exists
    - ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Bold Italic.ttf"
      register: bold_italic
    - name: "Bold Italic"
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/MesloLGS NF Bold Italic.ttf"
      when: not bold_italic.stat.exists
  when: ansible_pkg_mgr != "homebrew"

- name: .zshrc.omz
  ansible.builtin.template:
    src: templates/zshrc.omz.j2
    dest: "{{ lookup('env', 'HOME') }}/.zshrc.omz"

- name: .p10k.zsh
  ansible.builtin.copy:
    src: files/p10k.zsh
    dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
