- name: Install flock
  community.general.homebrew:
    name: flock
    state: present

- name: Check flock path
  ansible.builtin.command: which flock
  changed_when: False
  register: flockpath

- name: Disable cron email
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: ""

- name: Ansible-pull cron job
  ansible.builtin.cron:
    name: ansible-pull quarter-hourly
    minute: "*/15"
    job: "{{ flockpath.stdout }} -n /tmp/ansible-pull-lock {{ lookup('env', 'HOME') }}/.setup/run-ansible-pull.sh -o"

- name: Ansible-pull reboot cron
  ansible.builtin.cron:
    name: ansible-pull reboot
    special_time: reboot
    job: "{{ lookup('env', 'HOME') }}/.setup/run-ansible-pull.sh -e ON_REBOOT=true"

- name: Check ZSH path
  ansible.builtin.command: which zsh
  changed_when: False
  register: zshpath

- name: Check ZSH stat
  ansible.builtin.stat:
    path: "{{zshpath.stdout}}"
  register: zsh_stat

- name: Setup ZSH Environment
  block:
    - name: Install OMZ
      ansible.builtin.command:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

    - name: Install powerlevel10k theme
      community.general.homebrew:
        name: romkatv/powerlevel10k/powerlevel10k
        state: present

    - name: .zshrc
      ansible.builtin.template:
        src: zshrc.j2
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"

    - name: .p10k.zsh
      ansible.builtin.copy:
        src: files/p10k.zsh
        dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"

  when: zsh_stat.stat.executable is defined and zsh_stat.stat.executable

- name: .vimrc
  ansible.builtin.copy:
    src: files/vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: .gitconfig
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.file', 'files/gitconfig') }}"