- name: Install flock
  community.general.homebrew:
    name: flock
    state: present

- name: Ansible-pull cron job
  ansible.builtin.cron:
    name: ansible-pull quarter-hourly
    minute: "*/15"
    job: flock -n /tmp/ansible-pull-lock ~/.setup/run-ansible-pull.sh -o

- name: Ansible-pull reboot cron
  ansible.builtin.cron:
    name: ansible-pull reboot
    special_time: reboot
    job: ~/.setup/run-ansible-pull.sh -e ON_REBOOT=true

- name: Check ZSH path
  ansible.builtin.command: which zsh
  register: zshpath

- name: Check ZSH stat
  ansible.builtin.stat:
    path: "{{zshpath.stdout}}"
  register: zsh_stat

- name: Show zsh stat
  ansible.builtin.debug:
    var: zsh_stat.stat.executable

- name: Get homebrew prefix
  ansible.builtin.command: brew --prefix
  register: homebrew_prefix

- name: Setup ZSH Environment
  block:
    - name: Install OMZ
      ansible.builtin.command:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

    - name: Get homebrew prefix
      ansible.builtin.command: brew --prefix
      register: homebrew_prefix

    - name: Install powerlevel10k theme
      community.general.homebrew:
        name: romkatv/powerlevel10k/powerlevel10k
        state: present

    - name: .zshrc
      ansible.builtin.template:
        src: zshrc.j2
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"
      vars:
        home_dir: "{{ lookup('env', 'HOME') }}"
        brew_prefix: "{{ homebrew_prefix }}"

    - name: .p10k.zsh
      ansible.builtin.copy:
        src: files/p10k.zsh
        dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"

  when: zsh_stat.stat.executable is defined and zsh_stat.stat.executable

- name: .vimrc
  ansible.builtin.copy:
    src: files/vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: .gitconfig
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.file', 'files/gitconfig') }}"